AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  Exclude:
    - 'test/**/*'
    - 'tests/**/*'

Style/FrozenStringLiteralComment:
  Enabled: true

Style/Documentation:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/BlockNesting:
  Enabled: false

Naming/MethodName:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false

Style/GlobalVars:
  Enabled: false
Style/OptionalBooleanParameter:
  Enabled: false
Style/CombinableLoops:
  Enabled: false
Style/HashEachMethods:
  Enabled: false
Style/RescueStandardError:
  Enabled: false
Style/RescueModifier:
  Enabled: false

Lint/EmptyClass:
  Enabled: false
Lint/EmptyBlock:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
