AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  Exclude:
    - 'test/**/*'
    - 'tests/**/*'

Metrics/MethodLength:
  Max: 120
Metrics/ModuleLength:
  Max: 1200
Metrics/AbcSize:
  Max: 120
Metrics/CyclomaticComplexity:
  Max: 50
Metrics/PerceivedComplexity:
  Max: 60
Metrics/BlockLength:
  Max: 100

Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: true
