AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  Exclude:
    - 'test/**/*'
    - 'tests/**/*'
    - 'ElementaroInfo/**/*'
    - 'elementaro_autoinfo.rb'

Metrics/MethodLength:
  Max: 20

Style/FrozenStringLiteralComment:
  Enabled: true
